[package]
name = "awkernel_drivers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
bitflags = "2.3"

[dependencies.x86_64]
version = "0.14"
optional = true

[dependencies.acpi]
git = "https://github.com/sun-jacobi/acpi.git"
optional = true


[dependencies.awkernel_lib]
path = "../awkernel_lib"
default-features = false


[dependencies.awkernel_aarch64]
path = "../awkernel_aarch64"
optional = true


[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2"

[features]
default = []
x86 = ["awkernel_lib/x86","dep:acpi", "dep:x86_64"]
rv32 = ["awkernel_lib/rv32"]
aarch64 = ["awkernel_lib/aarch64", "dep:awkernel_aarch64"]


[dependencies.smoltcp]
version = "0.8.0"
default-features = false
features = [
    "alloc", 
    "log", 
    "socket-udp", 
    "socket-tcp", 
    "proto-ipv4", 
    "proto-ipv6",
    "medium-ethernet", 
]

