[package]
name = "t4os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memac = "0.5"
synctools = "0.4"
log = "0.4"
bitflags = "1.3"
acpi = "4.1"
pin-project-lite = "0.2"

[dependencies.futures]
version = "0.3"
default-features = false
features = ["alloc", "async-await", "cfg-target-has-atomic"]

[dependencies.x86_64]
version = "0.14"
optional = true

[dependencies.uart_16550]
version = "0.2"
optional = true

[dependencies.bootloader_api]
version = "0.11"
optional = true

[dependencies.unwinding]
version = "0.1"
default-features = false
features = ["unwinder", "panic"]

[dependencies.libc]
version = "0.2"
optional = true

[dependencies.crossbeam-queue]
version = "0.3"
default-features = false
features = ["alloc"]

[features]
default = ["x86"]
x86 = ["unwinding/fde-static", "unwinding/personality", "dep:uart_16550", "dep:x86_64", "dep:bootloader_api"]
aarch64 = ["unwinding/fde-static", "unwinding/personality"]
raspi3 = ["aarch64", "raspi"]
raspi4 = ["aarch64", "raspi"]
raspi = []
linux = ["libc", "unwinding/panic-handler", "unwinding/fde-phdr-dl", "unwinding/personality"]
