[package]
name = "t4os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memac = "0.5.0"
synctools = "0.3.1"
log = "0.4"
gimli = { version = "0.27", default-features = false, features = ["read-core"] }

[dependencies.x86_64]
version = "0.14"
optional = true

[dependencies.uart_16550]
version = "0.2"
optional = true

[dependencies.bootloader]
version = "0.10.13"
optional = true

[dependencies.unwinding]
version = "0.1"
default-features = false
features = ["unwinder", "personality", "panic"]

[dependencies.libc]
version = "0.2"
optional = true

[features]
default = ["raspi3"]
x86 = ["unwinding/fde-static", "dep:uart_16550", "dep:x86_64", "dep:bootloader"]
aarch64 = ["unwinding/fde-static"]
raspi3 = ["aarch64", "raspi"]
raspi4 = ["aarch64", "raspi"]
raspi = []
linux = ["libc", "unwinding/panic-handler", "unwinding/fde-phdr-dl"]

[package.metadata.bootloader]
map-physical-memory = true
physical-memory-offset = "0x8000_0000_0000" # Phisical memory is placed at 128TiB of virtual memory