[package]
name = "t4os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memac = "0.5"
synctools = "0.3"
log = "0.4"
bitflags = "1.3"
acpi = "4.1"

[dependencies.unwinding]
version = "0.1"
default-features = false
features = ["unwinder", "panic"]

[dependencies.libc]
version = "0.2"
optional = true

[dependencies.t4os_async_lib]
path = "../t4os_async_lib"
default-features = false

[dependencies.t4os_lib]
path = "../t4os_lib"

[target.'cfg(target_arch = "aarch64")'.dependencies]
t4os_aarch64 = { path = "../t4os_aarch64" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14"
bootloader_api = "0.11"
uart_16550 = "0.2"

[features]
default = []
no_std_unwinding = ["unwinding/fde-static", "unwinding/personality"]
x86 = ["unwinding/fde-static", "unwinding/personality"]
raspi3 = ["raspi", "no_std_unwinding"]
raspi4 = ["raspi", "no_std_unwinding"]
raspi = []
linux = ["libc", "unwinding/panic-handler", "unwinding/fde-phdr-dl", "unwinding/personality", "t4os_lib/linux"]
