[package]
name = "t4os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memac = "0.5"
synctools = "0.3"
log = "0.4"
bitflags = "1.3"
acpi = "4.1"
rlsf = "0.2.0"

[dependencies.unwinding]
version = "0.1"
default-features = false
optional = true
features = ["unwinder", "panic", "personality", "fde-static"]

[dependencies.libc]
version = "0.2"
optional = true

[dependencies.userland]
path = "../userland"

[dependencies.t4os_async_lib]
path = "../t4os_async_lib"
default-features = false

[dependencies.t4os_lib]
path = "../t4os_lib"
default-features = false

[dependencies.t4os_aarch64]
path = "../t4os_aarch64"
optional = true

[dependencies.x86_64]
version = "0.14"
optional = true

[dependencies.bootloader_api]
version = "0.11"
optional = true

[dependencies.uart_16550]
version = "0.2"
optional = true

[features]
default = ["raspi3"]
no_std_unwinding = ["dep:unwinding"]
x86 = ["no_std_unwinding", "t4os_lib/x86", "dep:x86_64", "dep:bootloader_api", "dep:uart_16550"]
raspi3 = ["raspi", "no_std_unwinding"]
raspi4 = ["raspi", "no_std_unwinding"]
raspi = ["aarch64"]
aarch64 = ["dep:t4os_aarch64", "t4os_lib/aarch64"]
linux = ["std", "dep:libc"]
std = ["t4os_lib/std", "t4os_async_lib/std"]
