[package]
name = "t4os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.10.13"
memac = "0.5.0"
uart_16550 = "0.2"
log = "0.4"
uefi = "0.18"
x86_64 = "0.14"

[dependencies.unwinding]
version = "0.1"
default-features = false
features = ["unwinder", "fde-static", "personality", "panic"]

[package.metadata.bootloader]
map-physical-memory = true
physical-memory-offset = "0x8000_0000_0000" # Phisical memory is placed at 128TiB of virtual memory
