[alias]
x86 = "build --package awkernel --no-default-features --features x86 --target x86_64-kernel.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
raspi3 = "build --package awkernel --no-default-features --features raspi3 --target aarch64-kernel.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
raspi4 = "build --package awkernel --no-default-features --features raspi4 --target aarch64-kernel.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
linux = "build --package awkernel --no-default-features --features linux"

test_awkernel_lib = "test --package awkernel_lib --no-default-features --features std"
test_awkernel_async_lib = "test --package awkernel_async_lib --no-default-features --features std"

check_no_std = "check --package awkernel -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem --quiet --message-format=json"
check_std = "check --package awkernel --quiet --message-format=json"

clippy_x86 = "clippy --package awkernel --no-default-features --features x86 --target x86_64-kernel.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
clippy_raspi3 = "clippy --package awkernel --no-default-features --features raspi3 --target aarch64-kernel.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
clippy_raspi4 = "clippy --package awkernel --no-default-features --features raspi4 --target aarch64-kernel.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
clippy_linux = "clippy --package awkernel --no-default-features --features linux"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-lc", "-C", "link-arg=-lpthread"]
