[package]
name = "awkernel_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
rlsf = "0.2"
synctools = "0.3"

[dependencies.libc]
version = "0.2"
optional = true

[dependencies.x86_64]
version = "0.14"
optional = true

[dependencies.acpi]
version = "4.1"
optional = true

[dependencies.bootloader_api]
version = "0.11"
optional = true

[dependencies.awkernel_aarch64]
path = "../awkernel_aarch64"
optional = true

[features]
default = ["std"]
x86 = ["dep:x86_64", "dep:acpi", "dep:bootloader_api"]
aarch64 = ["dep:awkernel_aarch64"]
rv32 = []
std = ["dep:libc"]
